apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ho408x9th-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ho408x9th-nodejs 
  name: ho408x9th-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ho408x9th-nodejs 
