apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ho408x9th-nodejs 
  janus-idp.io/tekton: ho408x9th-nodejs
  backstage.io/kubernetes-id: ho408x9th-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ho408x9th-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  